set term=xterm-256color
syntax enable
filetype plugin indent on

set nocompatible
set ttyfast
set encoding=utf-8 nobomb
set scrolloff=5

set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab
set backspace=indent,eol,start
set number
set ruler
set syntax=on
set termguicolors
set display+=lastline
set hlsearch

" tab navigation shortcuts for `vim -p ...`
set tabpagemax=200
nmap <C-j> :tabp<CR>
imap <C-j> <ESC>:w<CR>:tabp<CR>
nmap <C-k> :tabn<CR>
imap <C-k> <ESC>:w<CR>:tabn<CR>
nmap <C-m> :tabnew<CR>
nmap <C-n> :NERDTreeToggle<CR>
imap <C-n> :w<CR>:tabnew<CR>:NERDTreeToggle<CR>
nmap <C-p> :w<CR>:CtrlP<CR>
imap <C-p> <ESC>:w<CR>:tabnew<CR>:CtrlP<Cr>

let g:rustfmt_autosave = 1
