#!/usr/bin/env bash

set -eu +x -o pipefail

# Install tools
echo "[ELI DOTFILES] Installing tools..."
apt-get install -y \
  curl \
  wget \
  vim \
  jq \
  ripgrep \
  procps \
  shellcheck \
  exuberant-ctags \
  rbenv \
  htop \
  tree \
  tshark \
  iftop

# Install config files
echo "[ELI DOTFILES] Installing config files..."
cp $(pwd)/dotfiles/vimrc "$HOME/.vimrc"
cp $(pwd)/dotfiles/bashrc "$HOME/.bashrc"

# Install minimal Vim plugins
echo "[ELI DOTFILES] Installing Vim plugins..."
mkdir -p "$HOME/.vim/pack/plugins/start"
git clone https://github.com/fatih/vim-go.git "$HOME/.vim/pack/plugins/start/vim-go"
vim +'GoInstallBinaries' +qa;
git clone https://github.com/rust-lang/rust.vim "$HOME/.vim/pack/plugins/start/rust.vim"
git clone https://github.com/scrooloose/nerdtree "$HOME/.vim/pack/plugins/start/nerdtree"
git clone https://github.com/vim-airline/vim-airline.git "$HOME/.vim/pack/plugins/start/vim-airline"

# Register SSH keys from GitHub
echo "[ELI DOTFILES] Installing authorized SSH keys..."
mkdir -p "$HOME/.ssh"
curl --silent --fail "https://github.com/elireisman.keys" > "$HOME/.ssh/authorized_keys"

